doc: recent kconfig changes break doc generation
Instead of wildcards we now are using environment variables to set the
path to Kconfig files for board and architecture. This break
documentation generation for Kconfig variables.

Using the env variables, we now set the path to what it used to be to
restore previous behavior.

Also, when something like this happens in the future, we should abort on
doc creation failure.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

diff --git a/.shippable.yml b/.shippable.yml
--- a/.shippable.yml
+++ b/.shippable.yml
@@ -42,6 +42,10 @@ build:
             echo "- Building Documentation";
             echo "Commit range:" ${COMMIT_RANGE}
             make htmldocs
+            if [ "$?" != "0" ]; then
+              echo "Documentation build failed";
+              exit 1;
+            fi
             if [ -s doc/doc.warnings ]; then
               echo " => New documentation warnings/errors";
               cp doc/doc.warnings doc.warnings
