doc: filter doc gen warnings
Because of known issues with Sphinx/Breathe tools we're using
to generate doxygen-based comments for our API documentaion,
we're getting a bevy of warning messages written out.  As a
workaround for our CI system, we created a filter-known-issues
script to remove "expected" warnings from the output.  This patch
includes calling that filter script as part of the doc generation
so folks making local builds of the docs won't be tripped up by
all the warning messages.

(See https://github.com/sphinx-doc/sphinx/issue/2682 and
https://github.com/sphinx-doc/sphinx/issues/2683)

Fixes #1527

Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

diff --git a/doc/Makefile b/doc/Makefile
--- a/doc/Makefile
+++ b/doc/Makefile
@@ -10,6 +10,7 @@ SPHINXBUILD   = sphinx-build
 PAPER         =
 BUILDDIR     ?= _build
 DOC_TAG      ?= development
+TMP_EXT       = $$PPID.log
 
 # User-friendly check for sphinx-build
 ifeq ($(shell which $(SPHINXBUILD) >/dev/null 2>&1; echo $$?), 1)
@@ -79,7 +80,16 @@ kconfig: scripts/genrest/genrest.py
 prep: doxy content kconfig
 
 html: content kconfig
-	$(Q)$(SPHINXBUILD) -t $(DOC_TAG) -b html $(ALLSPHINXOPTS) $(BUILDDIR)/html
+	$(Q)$(SPHINXBUILD) -t $(DOC_TAG) -b html $(ALLSPHINXOPTS) \
+      $(BUILDDIR)/html > /tmp/doc-$(TMP_EXT) 2>&1;
+	$(Q)../scripts/filter-known-issues.py --config-dir \
+      ../.known-issues/doc /tmp/doc-$(TMP_EXT) > /tmp/doc-warnings-$(TMP_EXT) || \
+      (echo " ==> Error running filter-known-issues"; exit 1); \
+      if [ -s /tmp/doc-warnings-$(TMP_EXT) ]; then \
+        echo " => New documentation warnings/errors"; \
+        cat /tmp/doc-warnings-$(TMP_EXT); \
+        exit 1; \
+      fi;
 	@rm -rf samples
 	@rm -rf boards
 
