Revert "Merge branch 'main' into add_LC709203F_fuel_gauge_driver"
This reverts commit ceeddb98a750b6b8e7eb88f35e77a4355b21034c, reversing
changes made to 03c4e8aa7a188540b6caf8984d7c234cc586d368.

diff --git a/.github/workflows/pr_metadata_check.yml b/.github/workflows/pr_metadata_check.yml
--- a/.github/workflows/pr_metadata_check.yml
+++ b/.github/workflows/pr_metadata_check.yml
@@ -18,23 +18,15 @@ jobs:
     name: Prevent Merging
     runs-on: ubuntu-24.04
     steps:
-      - name: Checkout
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-
-      - name: Set up Python
-        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
-        with:
-          python-version: 3.12
-          cache: pip
-          cache-dependency-path: scripts/requirements-actions.txt
-
-      - name: Install Python dependencies
+      - name: Check for label
+        if: ${{ contains(github.event.*.labels.*.name, 'DNM') ||
+                contains(github.event.*.labels.*.name, 'TSC') ||
+                contains(github.event.*.labels.*.name, 'Architecture Review') ||
+                contains(github.event.*.labels.*.name, 'dev-review') }}
         run: |
-          pip install -r scripts/requirements-actions.txt --require-hashes
-
-      - name: Run the check script
-        run: |
-          ./scripts/ci/do_not_merge.py -p "${{ github.event.pull_request.number }}"
+          echo "Pull request is labeled as 'DNM', 'TSC', 'Architecture Review' or 'dev-review'."
+          echo "This workflow fails so that the pull request cannot be merged."
+          exit 1
 
   empty_pr_description:
     if: ${{ github.event.pull_request.body == '' }}
